apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty
  template:
    metadata:
      labels:
        app: faculty
    spec:
      containers:
        - name: faculty
          image: faculty-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-service
spec:
  selector:
    app: faculty
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort
